package com.herry.rssreader.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.herry.rssreader.models.Article;
import com.herry.rssreader.models.Channel;

import com.herry.rssreader.dao.ArticleDao;
import com.herry.rssreader.dao.ChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig channelDaoConfig;

    private final ArticleDao articleDao;
    private final ChannelDao channelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        channelDao = new ChannelDao(channelDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Channel.class, channelDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        channelDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

}
